# Generated by Django 3.2.9 on 2022-05-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('bid', models.FloatField(max_length=10)),
                ('url', models.URLField(max_length=128)),
                ('category', models.CharField(max_length=64)),
            ],
        ),
    ]
