# Generated by Django 3.2.9 on 2022-05-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_watchlist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='item',
            new_name='listing',
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
