# Generated by Django 3.2.9 on 2022-05-13 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_comment_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userbought', models.CharField(max_length=64)),
                ('item', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=2, max_digits=32)),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='item',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
