# Generated by Django 3.2.9 on 2022-05-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20220513_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='oc',
            field=models.BooleanField(default=True),
        ),
    ]
