# Generated by Django 3.2.9 on 2022-05-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auction_oc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='winner',
        ),
        migrations.AddField(
            model_name='auction',
            name='winner',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
